import Head from "next/head";
import Image from "next/image";
import { HStack, Heading, Text, VStack } from "@chakra-ui/react";

export const HomeScreen = () => (
  <>
    <Head>
      <title>happy - Birthday Reminder</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <HStack height={"100vh"} justifyContent={"space-evenly"}>
      <VStack alignItems={"flex-start"}>
        {/* Name of the app */}
        <Text as={"h1"} fontSize={"xx-large"}>happy</Text>
        <Text color="gray" fontSize={"large"}>Birthday Reminder App</Text>
        <Text color={"blue"}>never forget a friend's birthday</Text>
        {/* Download Button to IOS */}
      </VStack>
      <VStack>
        <Image src="/happy.png" alt="happy" width={200} height={200} />
        {/* Video or Images showcasing the app */}
      </VStack>
    </HStack>
  </>
);
